# Generated by Django 3.2.9 on 2021-11-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=128, null=True)),
                ('last_name', models.CharField(max_length=128, null=True)),
                ('looking_for_projects', models.BooleanField(default=True)),
                ('bio', models.CharField(blank=True, max_length=1280, null=True)),
                ('profile_picutre', models.CharField(max_length=10000, null=True)),
                ('video_link', models.CharField(max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=1280)),
                ('persons', models.ManyToManyField(to='api_app.Person')),
            ],
        ),
    ]
